### ISSUE TITLE
IRB Determination letter

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#105]
Hi @ErinBecker, I don't think the correct IRB letter is on the **OUR IMPACT**/Assessment [page](https://carpentries.org/assessment/).

**Comment by ErinBecker** [comment]
The IRB letter that is linked right now is our original determination letter. Since then, we have submitted three amendments / modifications and received three additional IRB determination letters. Should we have all 8 of these files (original application, 3 modifications, 4 decision letters) linked on the assessment page?

**Comment by kariljordan** [comment]
I'd say the most recent determination letter will suffice. If anyone wants more they can contact us. Do you think there are people out there who would be interested in checking out our application to see how to put one together for their own Carpentries research? If so, maybe the original application and the most recent determination letter with a note saying we've made amendments/modifications?

**Comment by weaverbel** [comment]
@ErinBecker Can I close this issue?

**Comment by ErinBecker** [comment]
Please leave open for now @weaverbel. I'll add this to my list to take care of and will close when I have.

**Comment by maneesha** [comment]
@ErinBecker  are you still working on this?
