### ISSUE TITLE
Include map on members page

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1166]
PR #1163 builds the membership list from data in AMY.  Once that is merged, we'd also like to include a map view of all memberships.  This is fairly straightforward to implement except for how we handle listing consortium members.  I'd like to get feedback from people on the Core Team Membership Team
(tagging @Al-Obayuwana  @elletjies  @Talishask  for now) about how we might handle listing consortium members on the map.  

* Do we identify them by their main organization (the signatory)? 
* Do we find the midpoint of all organizations? (so the point on the map doesn't actually reflect a location of the cornsortium?)
* Do we list locations of all organizations? (so one consortium membership will show up as several points on the map?)
* Any other ideas?

**Comment by Talishask** [comment]
I like the idea of using the main organisation or signatory for a few reasons. Consortiums are difficult because sometimes they have a handful of members (2-10) and other times there could be more (11+). If we were to add points for all of the consortium members we might end up with significantly more points than the members on our list. So it might be good to match what we do on the map with how we list our members.

**Comment by maneesha** [comment]
Fixed with https://github.com/carpentries/carpentries.org/pull/1270

**Comment by Al-Obayuwana** [comment]
-- Please reply above this line --


Hello,

Thank you for your email. Due to the holiday season, we will have a
reduced team attending to this inbox through 4 January. If this is not
an urgent matter, please expect a response following our return to
work in January.

If this is an urgent matter, please email ***@***.*** and
indicate "URGENT" in your email header and someone from our team will
be in contact with you as soon as possible.

Best & Be Well,
Membership Team
