### ISSUE TITLE
Missing footnotes at 2022-05-05-workbench-beta.md

### ISSUE THREAD

**Issue by annajiat** [carpentries/carpentries.org-archive#1396]
At https://carpentries.org/blog/2022/05/workbench-beta

Under "Beta Logistics"
the footnote for non-reversible[1](https://carpentries.org/blog/2022/05/workbench-beta/#fn:1)
is not leading to a text. Should there be a footnote?

Under "Website URLs"
Should the example URLs be replaced with plain text as the hyperlinks don't lead anywhere or should it be replaced with links from a lesson which already signed-up?
https://datacarpentry.github.io/r-novice-gapminder
https://lessons.datacarpentry.org/r-novice-gapminder

Under "Pre-Beta"
the footnote for new format[1](https://carpentries.org/blog/2022/05/workbench-beta/#fn:1).
is not leading to a text. 
Should there be a footnote?
Should it be numbered 2 since we already have "non-reversible" as footnote 1 

Under "Beta"
It is same for the 3rd footnote for
new infrastructure[1](https://carpentries.org/blog/2022/05/workbench-beta/#fn:1)

**Comment by zkamvar** [comment]
### Regarding footnotes

This appears to be an issue with the CSS behavior for the carpentries.org site and it's one of those things that's complex enough that I don't have the knowledge of how to fix it. The footnote exists, you just have to scroll up.

### URLs

I agree with this (though that datacarpentry URL is mea culpa because I had incorrectly assumed that r-novice-gapminder was in the DataCarpentry lesson program)

**Comment by annajiat** [comment]
@rahman9909
Please see if you can help.
