### ISSUE TITLE
drop down nav menus don't disappear - overlap

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/carpentries.org-archive#14]
The drop down navigation menus don't disappear when you move your mouse away from one of them, leading to lateral overlap between navigation menus.

**Comment by jduckles** [comment]
Can you reproduce, they do for me.

**Comment by weaverbel** [comment]
Same for me

Belinda Weaver
Community and Communications Lead
The Carpentries
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by maneesha** [comment]
This happens if instead of just hovering over a menu heading, you click on the menu heading and then mouse over to another menu heading.

The current SWC and DC websites do  the same thing.

**Comment by jduckles** [comment]
I can't reproduce in:
* Chrome -  65.0.3325.181 
* Firefox - 58.0.2 
* Safari - 11.0.3

**Comment by jduckles** [comment]
This is how it works for me. Do you see something different @ErinBecker? 

![](https://jduckles-dropshare.s3-us-west-2.amazonaws.com/Screen-Recording-2018-04-10-14-13-46.gif)

**Comment by maneesha** [comment]
This is what I see.  Note this happens if you activate a menu by clicking on the heading.  It stays active when you hover over other headings.   If you activate a heading by hovering over it, then it behaves as what  @jduckles  shared.  Both the existing DC and SWC websites do the same thing.  I've tested this on Chrome & Firefox in Ubuntu and Windows.


![swc_ff](https://user-images.githubusercontent.com/829690/38559254-87dea758-3ca0-11e8-94d8-0d7dc65e77f3.gif)
![carpentries_chrome](https://user-images.githubusercontent.com/829690/38559256-884b8da0-3ca0-11e8-9a5a-8de4c04021ed.gif)

**Comment by jduckles** [comment]
I can only duplicate that by hitting "Tab" a few times (to move "focus" to the menu links, dotted line around "about" in @maneesha's first gif above). I think this may be some kind of browser assistive setting. If I click on one of the headings it takes me to the link for that heading.

**Comment by maneesha** [comment]
That's really weird.  I've tried it across several browsers, across several  OSs, owned by different people.... I can't imagine they would all have the same browser assistive setting.

**Comment by jduckles** [comment]
If I click anywhere in the top-level of the menu, it takes me to the link for that level of the menu as defined in: https://github.com/carpentries/carpentries.org/blob/gh-pages/_data/navigation.yml

**Comment by jduckles** [comment]
I'm going to say won't fix on this one as it is the same behavior as SWC and DC websites. Seems to be a theme problem.

**Comment by ErinBecker** [comment]
It's not causing problems for me anymore. Thanks for looking into this.
