### ISSUE TITLE
Misleading deprecated checkout instructions

### ISSUE THREAD

**Issue by ampartridge** [carpentries/carpentries.org-archive#1742]
The checkout instructions [described here](https://carpentries.org/blog/2022/09/checkout-project/) are outdated. As a new instructor, this was confusing, especially as it was the top google result for 'carpentries checkout tasks'.

[This post](https://carpentries.org/blog/2023/08/checkout_changes/) details the new instructions, as does [this page](https://carpentries.github.io/instructor-training/checkout).

**Comment by maneesha** [comment]
Thanks for raising this issue @ampartridge 
Blog posts are generally intended to reflect information and status at the point in time when the blog post was published. We don't want to edit the blog post itself because we don't want to re-write history.  In the interest of clarity and keeping this information accessible and discoverable, I am adding a note to the top of the post linking to current information.
