### ISSUE TITLE
Update Code of Conduct Governance Liaison

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#1770]
On the [Code of Conduct Committee page](https://carpentries.org/coc-ctte/) we link to an Executive Council liaison. This will be removed with the upcoming PR about all the governance changes on 1 Feb 2024 and should be updated when a new Board liaison is confirmed.

**Comment by maneesha** [comment]
@kariljordan  Do we have a CoC Board Liaison yet?

**Comment by kariljordan** [comment]
We do not. I will check with the Board and CoCc about whether this role is still helpful/useful.

**Comment by kariljordan** [comment]
The Board will vote to appoint a CoCc liaison at the Q2 meeting on 7 May.

**Comment by kariljordan** [comment]
@maneesha the liaison is @jsteyn

**Comment by maneesha** [comment]
Thanks @kariljordan 

@jsteyn Can you share a bio so we can add you to the page here: https://carpentries.org/coc-ctte/

**Comment by jsteyn** [comment]
Is this okay?

[Jannetta Steyn](https://github.com/jsteyn) is a senior research software engineer at Newcastle university. She has been an instructor since 2020 and instructor trainer since 2021. She is also the convenor of the [CarpentriesOffline](https://carpentriesoffline.org/) development team. Jannetta is an elected member of the Board of Directors and serves as the liaison to the Code of Conduct committee.

**Comment by maneesha** [comment]
Thanks @jsteyn 
I have put in a PR to make this change and tagged you and @kariljordan  for review.
