### ISSUE TITLE
'What is a workshop?' web page

### ISSUE THREAD

**Issue by weaverbel** [carpentries/carpentries.org-archive#245]
Opening comments on this page - please record issues here or do a PR against the file `workshops.md` in the `pages` folder.

**Comment by kariljordan** [comment]
I went through the **what is a workshop** page and it's very clear what the benefits are. I have no pressing changes in mind.

**Comment by mtreg** [comment]
I was just visiting the page and noticed the text describing Library Carpentry workshops is formatted as a code block rather than rendered html, as outlined in Blue in the attached image - I imagine this isn't the intended appearance.

Hope this helps - thanks to Carpentries staff and other contributors for their great work!

![image](https://user-images.githubusercontent.com/8225986/49198382-d2921880-f360-11e8-8d04-e2821f5c2166.png)

**Comment by fmichonneau** [comment]
thanks for catching this @mtreg It should be fixed shortly.

**Comment by maneesha** [comment]
Closing - appears to be resolved.
