### ISSUE TITLE
Where should "Our Impact" go?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#479]
The "Our Impact"  menu option (which goes to our Assessment page) is currently under "Learn."  Would this be better under "About" instead, as the reports are not just about workshops?

Feedback from @kariljordan  or @serahrono would be appreciated - I can make the change from there.

**Comment by kariljordan** [comment]
I'm remembering the initial conversation we had when we added the the assessment info, and I think it fits best under **Learn** because people can learn not only about workshops, but about the impact our workshops and programs are having. Also, there are already a lot of drop downs under the **About** drop down and it's starting to look crowded :)

**Comment by maneesha** [comment]
Thanks @kariljordan   - we will keep it as is.
