### ISSUE TITLE
Should we list voting members on our website?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries.org-archive#525]
The Software Carpentry website historically has listed individual voting members.  See screenshot: 
![image](https://user-images.githubusercontent.com/829690/63442938-ef481200-c401-11e9-8035-c335df9f279f.png)

However both the voting qualifications and the list itself are out of date.  For now I am having it redirect to the voting eligibility guidelines in the handbook.  On the SWC page, it was a manually built page (not direct from an AMY feed).   Should we be listing individual voting members like this on The Carpentries site?  Seeking suggestions from the Leadership Team (
@tracykteal @ErinBecker @elizabethwilliams8  @kariljordan) and Executive Council (@amyehodge @k8hertweck @rgaiacs @elliewix @kcranston @lexnederbragt  
@josleecshl @mesfind )

If we decide to have a page like this we will have to consider how to keep this up to date.  Is it to be updated with each election?  An ongoing live build?  Something else?

**Comment by tracykteal** [comment]
Posting lists of people should conform to the same guidelines as in 'share my information' in AMY. So, I don't think we should publicly post this list. Is this list up somewhere live on the SWC website now?

If we do decide we want to have this list it can be pulled from AMY using criteria from there, including if people want their information shared, so that it stays up to date without manual curation.

**Comment by amyehodge** [comment]
+1 to Tracy. We should conform to the permissions granted in AMY. Posting an incomplete list is not useful. I'm not sure what purpose posting a list would actually serve. Anywhere this exists online already should be taken down.

**Comment by maneesha** [comment]
I already took down the page.  I'll close this as it doesn't seem we want an equivalent page on The Carpentries site.

**Comment by tracykteal** [comment]
Great, thanks @maneesha
