### ISSUE TITLE
Links not working in CDH blog post

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#656]
I'm linking to the [CDH blog post](https://github.com/carpentries/carpentries.org/blob/gh-pages/_posts/2019/04/2019-04-03-curriculum-development-handbook.md) in an email and noticed that two of the links do not work.

- [Chapter 1: Conceptual elements](https://cdh.carpentries.org/conceptual-elements.html)
- [Chapter 5: Community development ](https://cdh.carpentries.org/community-development.html)

**Comment by maneesha** [comment]
@kariljordan Thanks for catching this.

@fmichonneau This looks like it is due to restructuring some of the pages.  I'm not as familiar with how the CDH is built. Is there a way to do redirect to/from like there is in jekyll pages?

**Comment by fmichonneau** [comment]
no there isn't a way to do redirects, the links will need to be udpated in the blog post.

**Comment by maneesha** [comment]
Thanks @fmichonneau 

Question for @ErinBecker  and @fmichonneau -- I always think of blog posts as ephemeral.  Their content is meant to represent one point in time, rather than being a dedicated source of information.  In this case, it's not just a matter of fixing a couple of broken links. The overall TOC of the CDH has changed.  I would recommend not changing the blog post itself, but maybe adding a line at the top with today's date, noting that the CDH structure has changed, and linking directly to the main page.  What do you think?

**Comment by ErinBecker** [comment]
That sounds great @maneesha  - could you put in a PR?

**Comment by fmichonneau** [comment]
fixed with #674
