### ISSUE TITLE
Update Annual Report on 'About Us' page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/carpentries.org-archive#825]
Hi:) 

The paragraph below on the [About Us](https://carpentries.org/about/) page should be updated to include the 2019 Annual Report:

Here you will find a range of useful information about our work. For more information on all things Carpentries, see The Carpentries Handbook and for a summary of our impact and operations, see our Annual Report.

Thanks!

**Comment by maneesha** [comment]
Thanks for bringing this up @kariljordan 
Would you like to link directly to the 2019 Annual Report, or would you like to link to the general annual report page: https://carpentries.org/reports/

I would recommend linking to the general annual report page, so that we do not have to update this every year.

**Comment by kariljordan** [comment]
Great idea @maneesha. Linking to the reports page is a great idea.
